import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { Providers } from "./provider";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning // <-- This stops React from panicking when next-themes modifies this element
    >
      <body >

          <Providers>
            <main className="flex-1 w-full">
            <Navbar/>
            {children}
            <Footer/>
          </main> 
          </Providers>
          
      </body>
    </html>
  );
}
